name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  shared_preferences: ^2.0.17
  flutter_launcher_icons: ^0.12.0
  google_sign_in: ^6.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#42a5f5"

flutter_icons:
  android: "sde_chat"
  ios: true
  image_path: "assets/sde_chat.png"
  min_sdk_android: 21 